# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('organization', '0001_initial'), ('organization', '0002_organization_reseller'), ('organization', '0003_remove_organization_reseller'), ('organization', '0004_organization_reseller')]

    initial = True

    dependencies = [
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('reseller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reseller.Reseller')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
