# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20160404_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='extras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
