# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0003_organization_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('method', models.IntegerField(choices=[(1, 'fingerprint'), (2, 'rfid'), (3, 'password'), (4, 'manual')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Attendances',
                'verbose_name': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=400, verbose_name='Message')),
                ('sentOn', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='organization.Organization')),
            ],
            options={
                'verbose_name_plural': 'Notices',
                'verbose_name': 'Notice',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn', models.TimeField()),
                ('checkOut', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Shifts',
                'verbose_name': 'Shift',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=15, verbose_name='Unique Id')),
                ('dob', models.DateField()),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField()),
                ('preferences', django.contrib.postgres.fields.jsonb.JSONField()),
                ('photo', models.ImageField(upload_to='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='organization.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='organization.Staff'),
        ),
    ]
