# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20160119_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.CharField(default='', max_length=50, verbose_name="Admin's Contact Number"),
            preserve_default=False,
        ),
    ]
