# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20160303_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='uniqueId',
        ),
        migrations.AddField(
            model_name='staff',
            name='shift',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='organization.Shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='unique_id',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='Unique Id'),
            preserve_default=False,
        ),
    ]
