# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20160303_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Contact Info'),
        ),
    ]
