# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20160303_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
