# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_staff_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='shift',
        ),
        migrations.AddField(
            model_name='staff',
            name='shifts',
            field=models.ManyToManyField(related_name='staff', to='organization.Shift'),
        ),
    ]
