# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20160308_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='preferences',
        ),
    ]
