# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 10:47
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_calendar_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('holiday', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Calendar')),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='checkIn',
            new_name='beginning_in',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='checkOut',
            new_name='beginning_out',
        ),
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.AddField(
            model_name='shift',
            name='check_in',
            field=models.TimeField(default=datetime.datetime(2016, 3, 10, 10, 46, 34, 916164, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='check_out',
            field=models.TimeField(default=datetime.datetime(2016, 3, 10, 10, 46, 41, 706849, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='ending_in',
            field=models.TimeField(default=datetime.datetime(2016, 3, 10, 10, 46, 45, 362283, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='ending_out',
            field=models.TimeField(default=datetime.datetime(2016, 3, 10, 10, 46, 49, 913618, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='late_time',
            field=models.TimeField(default=datetime.datetime(2016, 3, 10, 10, 46, 58, 384163, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='leave_early_time',
            field=models.TimeField(default=datetime.datetime(2016, 3, 10, 10, 47, 12, 389132, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='off_duty_time',
            field=models.TimeField(default=datetime.datetime(2016, 3, 10, 10, 47, 17, 116802, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='on_duty_time',
            field=models.TimeField(default=datetime.datetime(2016, 3, 10, 10, 47, 20, 740185, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='organization.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.Day'),
            preserve_default=False,
        ),
    ]
