# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-03 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20160310_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
