# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseller', to=settings.AUTH_USER_MODEL),
        ),
    ]
