# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0002_auto_20151228_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseller',
            name='expiry_date',
        ),
    ]
