# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0003_remove_reseller_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='organization_creation_limit',
            field=models.IntegerField(default=1, help_text='The maximum number of organizations                                                       that can be created.'),
        ),
    ]
