# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0004_auto_20160109_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reseller',
            options={'ordering': ('-user__date_joined',), 'verbose_name': 'Reseller', 'verbose_name_plural': 'Resellers'},
        ),
    ]
